services:
  graph:
    container_name: graph
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./output:/output
    working_dir: /app
    tty: true
