const sections = [
  ['WORKSPACE', [['Overview', 'home']]],
  ['USERS', [['User Intelligence', 'users']]],
  ['SECURITY', [['MFA Coverage', 'shield-check'], ['Conditional Access', 'lock'], ['Admin Roles', 'crown'], ['Risky Users', 'alert-triangle'], ['Sign-in Activity', 'activity']]],
  ['PRODUCTIVITY', [['Exchange', 'mail'], ['OneDrive', 'cloud'], ['SharePoint', 'layout-sidebar'], ['Teams', 'messages']]],
  ['LICENSE', [['Utilization', 'chart-bar'], ['Optimizer', 'stars'], ['Parking Report', 'parking']]],
  ['PROTECTION', [['Defender for Office 365', 'shield'], ['Cloud App Discovery', 'search'], ['DLP Violations', 'alert-circle'], ['Sensitivity Labels', 'tag']]],
  ['IDENTITY', [['Guest Users', 'user-plus'], ['Auth Methods', 'key'], ['Named Locations', 'map-pin']]],
  ['COMPLIANCE', [['Intune Devices', 'device-laptop'], ['Compliance Policies', 'clipboard-list'], ['Mobile Apps', 'device-mobile-rotated']]],
  ['SETTINGS', [['API Keys', 'terminal'], ['Email Reports', 'send'], ['Tenants', 'building']]]
];
const columns = {
  IDENTITY: ['display_name', 'upn', 'user_type', 'account_enabled', 'created_date_time', 'department', 'job_title', 'country'],
  SECURITY: ['mfa_registered', 'mfa_method', 'passwordless_capable', 'risk_level', 'risk_state', 'last_signin', 'last_signin_city', 'last_signin_country', 'last_signin_app', 'last_signin_risk'],
  LICENSE: ['license_names', 'license_count'], EXCHANGE: ['exchange_last_activity', 'emails_sent', 'emails_received', 'mailbox_size_mb'],
  TEAMS: ['teams_last_activity', 'teams_chat_count', 'teams_call_count', 'teams_meeting_count'], COMPLIANCE: ['device_count', 'device_compliant', 'device_os']
};
const defaults = ['display_name', 'upn', 'user_type', 'account_enabled', 'mfa_registered', 'risk_level', 'license_names', 'last_signin', 'exchange_last_activity', 'teams_last_activity'];
const labels = (name) => name.replace(/_/g, ' ').replace(/(^| )\w/g, (x) => x.toUpperCase());
const tooltips = {
  display_name: 'Full name of the user in Microsoft 365', upn: 'User Principal Name &mdash; the login email address', user_type: 'Member = internal employee, Guest = external user', account_enabled: 'Whether the account is active or disabled in Entra ID', created_date_time: 'When the account was created in this tenant', department: 'User department from Entra ID profile', job_title: 'User job title from Entra ID profile', country: 'Country from Entra ID profile',
  mfa_registered: 'Whether the user has registered an MFA method', mfa_method: 'MFA method registered (Authenticator, SMS, etc)', passwordless_capable: 'Whether the user can sign in without a password', risk_level: 'Account risk level from Entra ID Protection (none/low/medium/high). Requires Entra ID P2 license.', risk_state: 'Current risk state (atRisk, remediated, dismissed)', last_signin: 'Date and time of the user last sign-in', last_signin_city: 'City where the last sign-in originated', last_signin_country: 'Country where the last sign-in originated', last_signin_app: 'Application used during the last sign-in', last_signin_risk: 'Risk level detected during the last sign-in',
  license_names: 'Microsoft 365 licenses assigned to this user', license_count: 'Number of licenses assigned to this user', exchange_last_activity: 'Last date the user was active in Exchange or Outlook', emails_sent: 'Number of emails sent in the reporting period', emails_received: 'Number of emails received in the reporting period', mailbox_size_mb: 'Current mailbox size in megabytes',
  teams_last_activity: 'Last date the user was active in Microsoft Teams', teams_chat_count: 'Number of chat messages sent in Teams', teams_call_count: 'Number of calls made in Teams', teams_meeting_count: 'Number of meetings attended in Teams', device_count: 'Number of devices enrolled in Intune for this user', device_compliant: 'Whether the user device meets the Intune compliance policy', device_os: 'Operating system of the enrolled device'
};
const navigation = document.querySelector('#navigation'); const content = document.querySelector('#content'); const headerTitle = document.querySelector('#header-title');
sections.forEach(([section, items]) => { const heading = document.createElement('li'); heading.className = 'nav-item navbar-heading'; heading.textContent = section; navigation.appendChild(heading); items.forEach(([title, icon]) => { const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); const item = document.createElement('li'); item.className = 'nav-item'; item.innerHTML = `<a class="nav-link" href="#/${slug}" data-page="${slug}"><span class="nav-link-icon d-md-none d-lg-inline-block"><i class="ti ti-${icon}"></i></span><span class="nav-link-title">${title}</span></a>`; navigation.appendChild(item); }); });
let users = [], selected = [], sortKey = '', sortAsc = true;
let columnWidths = {};
let resizing = null;
const columnWidthsKey = 'v2_column_widths_user_intelligence';
const dateFields = new Set(['created_date_time', 'last_signin', 'exchange_last_activity', 'teams_last_activity']);
function value(cell, key) { if (cell === null || cell === undefined || cell === '') return '-'; if (key === 'license_names' && Array.isArray(cell)) return cell.join(', '); if (dateFields.has(key)) return new Date(cell).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); if (key === 'account_enabled') return `<span class="badge bg-${cell ? 'green' : 'red'}-lt">${cell ? 'Active' : 'Disabled'}</span>`; if (key === 'mfa_registered') return `<span class="intelligence-bool ${cell ? 'text-green' : 'text-red'}">${cell ? 'Check' : 'X'}</span>`; if (key === 'risk_level') return `<span class="badge risk-${String(cell).toLowerCase()}">${cell}</span>`; return String(cell); }
function save() { localStorage.setItem('v2_columns_user_intelligence', JSON.stringify(selected)); }
function saveColumnWidths() { localStorage.setItem(columnWidthsKey, JSON.stringify(columnWidths)); }
function startResize(event) { event.preventDefault(); event.stopPropagation(); const th = event.currentTarget.parentElement; resizing = { key: th.dataset.sort, startX: event.clientX, startWidth: th.offsetWidth }; document.body.classList.add('resizing-columns'); }
function resizeColumn(event) { if (!resizing) return; const width = Math.max(60, resizing.startWidth + event.clientX - resizing.startX); columnWidths[resizing.key] = width; const th = content.querySelector(`th[data-sort="${resizing.key}"]`); if (th) th.style.width = `${width}px`; }
function stopResize() { if (!resizing) return; resizing = null; document.body.classList.remove('resizing-columns'); saveColumnWidths(); }
function picker() { const panel = document.createElement('aside'); panel.className = 'column-picker'; panel.innerHTML = `<div class="d-flex justify-content-between align-items-center mb-3"><h3 class="m-0">Columns</h3><button class="btn-close" aria-label="Close"></button></div>`; Object.entries(columns).forEach(([group, names]) => { const section = document.createElement('div'); section.innerHTML = `<h4 class="text-secondary">${group}</h4>`; names.forEach((name) => { const row = document.createElement('label'); row.className = 'column-option'; row.draggable = true; row.dataset.column = name; row.innerHTML = `<span class="drag-handle">::</span><input type="checkbox" ${selected.includes(name) ? 'checked' : ''}> ${labels(name)}`; row.querySelector('input').onchange = (event) => { selected = event.target.checked ? [...selected, name] : selected.filter((item) => item !== name); save(); renderTable(); }; row.ondragstart = (event) => event.dataTransfer.setData('text/plain', name); row.ondragover = (event) => event.preventDefault(); row.ondrop = (event) => { const from = selected.indexOf(event.dataTransfer.getData('text/plain')); const to = selected.indexOf(name); if (from >= 0 && to >= 0) { selected.splice(to, 0, selected.splice(from, 1)[0]); save(); renderTable(); picker(); } }; section.appendChild(row); }); panel.appendChild(section); }); panel.querySelector('.btn-close').onclick = () => panel.remove(); document.body.appendChild(panel); }
function showTooltip(event) { const header = event.currentTarget; const tooltip = document.createElement('div'); tooltip.className = 'column-tooltip'; tooltip.setAttribute('role', 'tooltip'); tooltip.innerHTML = header.dataset.tooltip; document.body.appendChild(tooltip); const rect = header.getBoundingClientRect(); const viewportPadding = 8; const gap = 8; const tooltipRect = tooltip.getBoundingClientRect(); const left = Math.max(viewportPadding, Math.min(rect.left + rect.width / 2 - tooltipRect.width / 2, window.innerWidth - tooltipRect.width - viewportPadding)); tooltip.style.top = `${rect.bottom + gap}px`; tooltip.style.left = `${left}px`; header._tooltip = tooltip; }
function hideTooltip(event) { const tooltip = event.currentTarget._tooltip; if (tooltip) { tooltip.remove(); delete event.currentTarget._tooltip; } }
function renderTable() { const body = content.querySelector('.intelligence-table-wrap'); if (!body) return; const sorted = [...users].sort((a, b) => String(a[sortKey] ?? '').localeCompare(String(b[sortKey] ?? '')) * (sortAsc ? 1 : -1)); body.innerHTML = `<div class="table-responsive"><table class="table table-vcenter intelligence-table"><thead><tr>${selected.map((key) => `<th data-sort="${key}"${columnWidths[key] ? ` style="width: ${columnWidths[key]}px"` : ''}><span class="column-header-text" data-tooltip="${tooltips[key]}">${labels(key)}</span> <span class="sort-indicator">${sortKey === key ? (sortAsc ? 'up' : 'down') : ''}</span><div class="column-resize-handle"></div></th>`).join('')}
</tr></thead><tbody>${sorted.map((user) => `<tr>${selected.map((key) => `<td>${value(user[key], key)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; body.querySelectorAll('th').forEach((th) => { th.onclick = () => { sortAsc = sortKey === th.dataset.sort ? !sortAsc : true; sortKey = th.dataset.sort; renderTable(); }; th.querySelector('.column-resize-handle').onmousedown = startResize; const header = th.querySelector('.column-header-text'); header.addEventListener('mouseenter', showTooltip); header.addEventListener('mouseleave', hideTooltip); header.addEventListener('focus', showTooltip); header.addEventListener('blur', hideTooltip); }); }
window.addEventListener('mousemove', resizeColumn);
window.addEventListener('mouseup', stopResize);
async function renderUsers() { selected = JSON.parse(localStorage.getItem('v2_columns_user_intelligence') || 'null') || [...defaults]; try { columnWidths = JSON.parse(localStorage.getItem(columnWidthsKey) || '{}') || {}; } catch (error) { columnWidths = {}; } content.innerHTML = `<div class="page-header mb-4"><div><h2 class="page-title">User Intelligence</h2><div class="text-secondary">Loading users...</div></div><button class="btn btn-primary" id="columns-button">Columns</button></div><div class="card"><div class="card-body intelligence-table-wrap"><div class="spinner-border" role="status"></div></div></div>`; content.querySelector('#columns-button').onclick = picker; try { const response = await fetch('/api/intelligence/users', { headers: { Accept: 'application/json', 'X-API-Key': window.API_KEY || 'jruPSFSNmL7BjKjD_fp8J8MTgSNgTV1NHm3QJ4msdlk' } }); if (!response.ok) throw new Error(`Users request failed: ${response.status}`); const data = await response.json(); users = Array.isArray(data.users) ? data.users : []; content.querySelector('.text-secondary').textContent = `${users.length} users`; renderTable(); } catch (error) { content.querySelector('.intelligence-table-wrap').textContent = 'Unable to load users'; } }
function render() { const slug = window.location.hash.replace(/^#\/?/, '') || 'overview'; const link = navigation.querySelector(`[data-page="${slug}"]`) || navigation.querySelector('[data-page="overview"]'); const title = link ? link.querySelector('.nav-link-title').textContent : 'Overview'; navigation.querySelectorAll('.nav-link').forEach((navLink) => navLink.classList.toggle('active', navLink === link)); headerTitle.textContent = title; if (slug === 'user-intelligence') renderUsers(); else content.innerHTML = `<div class="page-header mb-4"><div><h2 class="page-title">${title}</h2><div class="text-secondary">This section is under construction</div></div></div><div class="card placeholder-card"><div class="card-body"><div class="placeholder-icon mb-3"><i class="ti ti-tool"></i></div><h3 class="card-title">${title}</h3><p class="text-secondary mb-0">Placeholder content for this assessment area.</p></div></div>`; }
window.addEventListener('hashchange', render); render();
