const sections = {
  WORKSPACE: [['Overview', 'home']],
  USERS: [['User Intelligence', 'users']],
  SECURITY: [['MFA Coverage', 'shield-check'], ['Conditional Access', 'lock'], ['Admin Roles', 'crown'], ['Risky Users', 'alert-triangle'], ['Sign-in Activity', 'activity']],
  PRODUCTIVITY: [['Exchange', 'mail'], ['OneDrive', 'cloud'], ['SharePoint', 'layout-2'], ['Teams', 'messages']],
  LICENSE: [['Utilization', 'chart-bar'], ['Optimizer', 'stars'], ['Parking Report', 'parking']],
  PROTECTION: [['Defender for Office 365', 'shield'], ['Cloud App Discovery', 'zoom-code'], ['DLP Violations', 'alert-circle'], ['Sensitivity Labels', 'tag']],
  IDENTITY: [['Guest Users', 'user-plus'], ['Auth Methods', 'key'], ['Named Locations', 'map-pin']],
  COMPLIANCE: [['Intune Devices', 'device-laptop'], ['Compliance Policies', 'clipboard-list'], ['Mobile Apps', 'device-mobile']],
  SETTINGS: [['API Keys', 'terminal'], ['Email Reports', 'send'], ['Tenants', 'building']]
};
const columns = ['display_name', 'upn', 'user_type', 'account_enabled', 'mfa_registered', 'risk_level', 'license_names', 'last_signin', 'department', 'job_title'];
const tips = { display_name: 'Full name of the user', upn: 'Login email address', user_type: 'Member or guest', account_enabled: 'Account active or disabled', mfa_registered: 'MFA method registered', risk_level: 'Account risk level', license_names: 'Licenses assigned to user', last_signin: 'Last sign-in date and time' };
const escape = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const label = (key) => key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
const format = (value, key) => { if (value === null || value === undefined || value === '') return '-'; if (Array.isArray(value)) return escape(value.join(', ')); if (key === 'account_enabled' || key === 'mfa_registered') return value ? '<span class="badge bg-green-lt">Yes</span>' : '<span class="badge bg-red-lt">No</span>'; if (key === 'last_signin') return escape(new Date(value).toLocaleDateString('en-GB')); return escape(value); };
function createPaginatedTable(config) {
  let selected = columns.slice(), page = 1, size = '10', sort = '', ascending = true, widths = {};
  const render = () => { const data = [...config.data].sort((a, b) => sort ? String(a[sort] ?? '').localeCompare(String(b[sort] ?? '')) * (ascending ? 1 : -1) : 0); const count = size === 'all' ? data.length : Number(size); const pages = Math.max(1, Math.ceil(data.length / (count || 1))); page = Math.min(page, pages); const rows = size === 'all' ? data : data.slice((page - 1) * count, page * count); config.container.innerHTML = `<div class="table-responsive"><table class="table table-vcenter"><thead><tr>${selected.map((key) => `<th data-key="${key}" title="${escape(tips[key] || '')}" style="${widths[key] ? `width:${widths[key]}px` : ''}">${label(key)}<span class="resize-handle"></span></th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${selected.map((key) => `<td>${format(row[key], key)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="d-flex justify-content-between align-items-center mt-3"><span>Showing ${data.length ? (page - 1) * count + 1 : 0}-${Math.min(page * count, data.length)} of ${data.length}</span><div class="btn-list"><select class="form-select form-select-sm page-size"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="all">All</option></select><button class="btn btn-sm page-prev">Previous</button><button class="btn btn-sm page-next">Next</button></div></div>`; config.container.querySelector('.page-size').value = size; config.container.querySelectorAll('th').forEach((th) => { th.onclick = (event) => { if (!event.target.classList.contains('resize-handle')) { sort = th.dataset.key; ascending = !ascending; render(); } }; }); config.container.querySelector('.page-size').onchange = (e) => { size = e.target.value; page = 1; render(); }; config.container.querySelector('.page-prev').onclick = () => { page = Math.max(1, page - 1); render(); }; config.container.querySelector('.page-next').onclick = () => { page = Math.min(pages, page + 1); render(); }; };
  render();
}
const nav = document.getElementById('navigation'), content = document.getElementById('page-content');
Object.entries(sections).forEach(([group, items]) => { nav.insertAdjacentHTML('beforeend', `<li class="navbar-heading">${group}</li>`); items.forEach(([name, icon]) => { const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); nav.insertAdjacentHTML('beforeend', `<li class="nav-item"><a class="nav-link" href="#/${slug}" data-page="${slug}"><span class="nav-link-icon"><i class="ti ti-${icon}"></i></span><span class="nav-link-title">${name}</span></a></li>`); }); });
async function render() { const slug = location.hash.replace(/^#\/?/, '') || 'overview'; const link = nav.querySelector(`[data-page="${slug}"]`) || nav.querySelector('[data-page="overview"]'); const name = link.querySelector('.nav-link-title').textContent; nav.querySelectorAll('.nav-link').forEach((item) => item.classList.toggle('active', item === link)); content.innerHTML = `<div class="container-xl"><div class="page-header mb-3"><h2 class="page-title">${name}</h2></div><div class="card"><div class="card-body" id="table-content">Loading...</div></div></div>`; if (slug === 'user-intelligence') { const response = await fetch('/api/intelligence/users', { headers: { 'X-API-Key': window.API_KEY } }); const payload = await response.json(); createPaginatedTable({ data: payload.users || [], container: document.getElementById('table-content') }); } }
document.getElementById('sidebar-toggle').addEventListener('click', function() { document.getElementById('sidebar').classList.toggle('d-none'); });
window.addEventListener('hashchange', render); render();
