"""Read-only security configuration collectors."""

from .sharepoint_tenant_settings import (
    SHAREPOINT_SETTINGS_ENDPOINT,
    SHAREPOINT_SETTINGS_PERMISSION,
    SharePointTenantSettingsCollector,
    SharePointTenantSettingsResult,
    normalize_sharing_capability,
)
from .entra_authorization_policy import (
    AUTHORIZATION_POLICY_ENDPOINT,
    AUTHORIZATION_POLICY_PATH,
    AUTHORIZATION_POLICY_PERMISSION,
    EntraAuthorizationPolicyCollector,
    EntraAuthorizationPolicyResult,
    normalize_allow_invites_from,
    EntraGuestDirectoryAccessCollector,
    GUEST_ACCESS_ENDPOINT,
    GUEST_ACCESS_PATH,
    GUEST_ACCESS_PERMISSION,
    GUEST_ACCESS_NORMALIZED_FIELD,
    normalize_guest_directory_access,
)
from .entra_ca_enforcement import (
    ConditionalAccessEnforcementCollector,
    ConditionalAccessEnforcementResult,
    aggregate_policy_states,
    aggregate_policy_security_counts,
    normalize_policy_state,
)
from .orchestration import SecurityExecutionSpec, SecurityOrchestrationError, SecurityOrchestrator
from .entra_user_consent import (
    AUTHORIZATION_POLICY_ENDPOINT as CONSENT_AUTHORIZATION_POLICY_ENDPOINT,
    AUTHORIZATION_POLICY_PATH as CONSENT_AUTHORIZATION_POLICY_PATH,
    AUTHORIZATION_POLICY_PERMISSION as CONSENT_AUTHORIZATION_POLICY_PERMISSION,
    EntraUserConsentCollector,
    EntraUserConsentResult,
    normalize_user_consent_policy,
)
from .entra_risky_consent import (
    AUTHORIZATION_POLICY_ENDPOINT as RISKY_CONSENT_AUTHORIZATION_POLICY_ENDPOINT,
    AUTHORIZATION_POLICY_PATH as RISKY_CONSENT_AUTHORIZATION_POLICY_PATH,
    AUTHORIZATION_POLICY_PERMISSION as RISKY_CONSENT_AUTHORIZATION_POLICY_PERMISSION,
    EntraRiskyConsentCollector,
    EntraRiskyConsentResult,
    normalize_risky_app_consent,
)
from .entra_global_admin import (
    EntraGlobalAdminCollector,
    EntraGlobalAdminResult,
    GLOBAL_ADMIN_ASSIGNMENTS_ENDPOINT,
    GLOBAL_ADMIN_ASSIGNMENTS_PATH,
    GLOBAL_ADMIN_PERMISSION,
    GLOBAL_ADMIN_ROLE_DEFINITION_ID,
)
from .entra_mfa_registration import MFA_REGISTRATION_ENDPOINT_ID, MfaRegistrationCollector, MfaRegistrationResult

__all__ = [
    "SHAREPOINT_SETTINGS_ENDPOINT",
    "SHAREPOINT_SETTINGS_PERMISSION",
    "SharePointTenantSettingsCollector",
    "SharePointTenantSettingsResult",
    "normalize_sharing_capability",
    "ConditionalAccessEnforcementCollector",
    "ConditionalAccessEnforcementResult",
    "aggregate_policy_states",
    "aggregate_policy_security_counts",
    "normalize_policy_state",
    "SecurityExecutionSpec",
    "SecurityOrchestrationError",
    "SecurityOrchestrator",
    "AUTHORIZATION_POLICY_ENDPOINT",
    "AUTHORIZATION_POLICY_PATH",
    "AUTHORIZATION_POLICY_PERMISSION",
    "EntraAuthorizationPolicyCollector",
    "EntraAuthorizationPolicyResult",
    "normalize_allow_invites_from",
    "EntraGuestDirectoryAccessCollector",
    "GUEST_ACCESS_ENDPOINT",
    "GUEST_ACCESS_PATH",
    "GUEST_ACCESS_PERMISSION",
    "GUEST_ACCESS_NORMALIZED_FIELD",
    "normalize_guest_directory_access",
    "EntraUserConsentCollector",
    "EntraUserConsentResult",
    "normalize_user_consent_policy",
    "CONSENT_AUTHORIZATION_POLICY_ENDPOINT",
    "CONSENT_AUTHORIZATION_POLICY_PATH",
    "CONSENT_AUTHORIZATION_POLICY_PERMISSION",
    "EntraRiskyConsentCollector",
    "EntraRiskyConsentResult",
    "normalize_risky_app_consent",
    "RISKY_CONSENT_AUTHORIZATION_POLICY_ENDPOINT",
    "RISKY_CONSENT_AUTHORIZATION_POLICY_PATH",
    "RISKY_CONSENT_AUTHORIZATION_POLICY_PERMISSION",
    "EntraGlobalAdminCollector",
    "EntraGlobalAdminResult",
    "GLOBAL_ADMIN_ASSIGNMENTS_ENDPOINT",
    "GLOBAL_ADMIN_ASSIGNMENTS_PATH",
    "GLOBAL_ADMIN_PERMISSION",
    "GLOBAL_ADMIN_ROLE_DEFINITION_ID",
    "MFA_REGISTRATION_ENDPOINT_ID", "MfaRegistrationCollector", "MfaRegistrationResult",
]
