"""Scenario registry.

The registry is a thin, deterministic map from ``scenario_id`` to
:class:`ScenarioDefinition`. It performs no I/O and no network access.

A small, built-in catalog ships with the framework so the Scenario
Agent has something to plan against out of the box. The catalog is
deliberately minimal: every entry corresponds to one supported action
type, declares its required delegated permissions, and is marked
non-destructive unless an explicit test scenario demands otherwise.

Callers may extend the catalog by passing additional definitions to
:class:`ScenarioRegistry`. Built-in definitions are immutable.
"""
from __future__ import annotations

from typing import Iterable, List, Mapping, Optional

from .actions import (
    ACTION_CREATE_CALENDAR_EVENT,
    ACTION_CREATE_FILE,
    ACTION_CREATE_GROUP_CONTENT,
    ACTION_CREATE_TEAMS_MESSAGE,
    ACTION_NOOP_VALIDATION,
    ACTION_SEND_MAIL,
    ACTION_UPDATE_FILE,
)
from .models import (
    IDENTITY_REQUIRED,
    RISK_LOW,
    RISK_MEDIUM,
    ScenarioDefinition,
)


# ---------------------------------------------------------------------------
# Built-in catalog
# ---------------------------------------------------------------------------


_BUILTIN_DEFINITIONS = (
    ScenarioDefinition(
        scenario_id="scenario.mail.send_test_message",
        name="Send a controlled test email",
        description=(
            "Send a deterministic test email as the selected actor. The "
            "subject and body are derived from the framework, not from "
            "arbitrary caller input."
        ),
        workload="mail",
        action_type=ACTION_SEND_MAIL,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("Mail.Send",),
        expected_observable_evidence=("mail_sent_marker",),
        cleanup_required=True,
        risk_level=RISK_LOW,
        destructive=False,
        enabled=True,
    ),
    ScenarioDefinition(
        scenario_id="scenario.calendar.create_test_event",
        name="Create a controlled calendar event",
        description=(
            "Create a deterministic calendar event in the actor's default "
            "calendar. Attendees and duration are bounded."
        ),
        workload="calendar",
        action_type=ACTION_CREATE_CALENDAR_EVENT,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("Calendars.ReadWrite",),
        expected_observable_evidence=("calendar_event_created_marker",),
        cleanup_required=True,
        risk_level=RISK_LOW,
        destructive=False,
        enabled=True,
    ),
    ScenarioDefinition(
        scenario_id="scenario.files.create_test_file",
        name="Create a controlled test file",
        description=(
            "Create a deterministic file in a known drive location. The "
            "file name is derived from the framework correlation marker."
        ),
        workload="files",
        action_type=ACTION_CREATE_FILE,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("Files.ReadWrite",),
        expected_observable_evidence=("file_created_marker",),
        cleanup_required=True,
        risk_level=RISK_LOW,
        destructive=False,
        enabled=True,
    ),
    ScenarioDefinition(
        scenario_id="scenario.files.update_test_file",
        name="Update a controlled test file",
        description=(
            "Update an existing file previously created by the files "
            "create scenario. Content size is bounded."
        ),
        workload="files",
        action_type=ACTION_UPDATE_FILE,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("Files.ReadWrite",),
        expected_observable_evidence=("file_updated_marker",),
        cleanup_required=True,
        risk_level=RISK_LOW,
        destructive=False,
        enabled=True,
        cleanup_scenario_id="scenario.files.cleanup_test_file",
    ),
    ScenarioDefinition(
        scenario_id="scenario.teams.post_test_message",
        name="Post a controlled test message",
        description=(
            "Post a deterministic test message to a known Teams "
            "channel. The message body is generated by the framework."
        ),
        workload="teams",
        action_type=ACTION_CREATE_TEAMS_MESSAGE,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("ChannelMessage.Send",),
        expected_observable_evidence=("teams_message_posted_marker",),
        cleanup_required=True,
        risk_level=RISK_MEDIUM,
        destructive=False,
        enabled=True,
    ),
    ScenarioDefinition(
        scenario_id="scenario.groups.post_test_content",
        name="Post a controlled group post",
        description=(
            "Create a deterministic post in a known test group. The "
            "subject and body are derived from the framework."
        ),
        workload="groups",
        action_type=ACTION_CREATE_GROUP_CONTENT,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("Group.ReadWrite.All",),
        expected_observable_evidence=("group_post_created_marker",),
        cleanup_required=True,
        risk_level=RISK_MEDIUM,
        destructive=False,
        enabled=True,
    ),
    ScenarioDefinition(
        scenario_id="scenario.framework.noop_validation",
        name="Validation-only scenario",
        description=(
            "A scenario that performs no Microsoft Graph action. Useful "
            "for plumbing tests and framework validation."
        ),
        workload="framework",
        action_type=ACTION_NOOP_VALIDATION,
        identity_requirement=IDENTITY_REQUIRED,
        required_delegated_permissions=("User.Read",),
        expected_observable_evidence=("noop_validation_marker",),
        cleanup_required=False,
        risk_level=RISK_LOW,
        destructive=False,
        enabled=True,
    ),
)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


class ScenarioRegistry:
    """Deterministic ``scenario_id`` -> :class:`ScenarioDefinition` map.

    The registry validates that every entry declares at least one
    required delegated permission and that its action type is one of
    the closed vocabulary values.
    """

    def __init__(self, extra: Optional[Iterable[ScenarioDefinition]] = None) -> None:
        self._definitions: dict = {}
        for definition in _BUILTIN_DEFINITIONS:
            self._add(definition)
        if extra:
            for definition in extra:
                self._add(definition)

    def _add(self, definition: ScenarioDefinition) -> None:
        if not definition.scenario_id:
            raise ValueError("scenario_id is required")
        if not definition.required_delegated_permissions:
            raise ValueError(
                "scenario {0!r} must declare at least one "
                "required_delegated_permission".format(definition.scenario_id)
            )
        self._definitions[definition.scenario_id] = definition

    # ----- Read-only views ------------------------------------------------

    def get(self, scenario_id: str) -> Optional[ScenarioDefinition]:
        """Return the :class:`ScenarioDefinition` for ``scenario_id``."""
        return self._definitions.get(scenario_id)

    def __contains__(self, scenario_id: object) -> bool:
        return scenario_id in self._definitions

    def __iter__(self):
        return iter(self._definitions)

    def __len__(self) -> int:
        return len(self._definitions)

    def scenario_ids(self) -> List[str]:
        """Return a stable list of registered scenario ids."""
        return list(self._definitions.keys())

    def values(self) -> List[ScenarioDefinition]:
        """Return a stable list of registered scenario definitions."""
        return list(self._definitions.values())

    def items(self) -> List:
        """Return a stable list of ``(scenario_id, definition)`` pairs."""
        return list(self._definitions.items())

    def to_dict(self) -> Mapping[str, object]:
        """Return a JSON-safe snapshot of the registry."""
        return {
            sid: definition.to_dict()
            for sid, definition in self._definitions.items()
        }


__all__ = ["ScenarioRegistry"]